version: '3.7'
services:
  frontend:
    image: frontend
    build: ./frontend
  backend:
    image: backend
    build: ./backend
    environment:
      DATABASE_URI: mysql+pymysql://admin:Password1234@database:3306/users
      SECRET KEY: Password1234!
  mysql:
    image: mysql:5.7
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=Password1234!  
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
