- name: Install curl
  apt:
    name: curl
    state: latest
    become: true
    update_cache: true

- name: Install kubectl
  apt_key:
    url: "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"

- name: executable kubectl
  file: 
    dest: ./kubectl
    mode: a+x

- name: move file to path and set permissions
  copy:
    src: ./kubectl
    dest: /usr/local/bin/kubectl 

