apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5001
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: abdulshaker/backend
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: secretsql
              key: database-uri
        - name: SECRET_KEY
          value: "Password1234!"
        ports:
        - containerPort: 5001





